### ISSUE TITLE
streams kept open unexpectedly

### ISSUE THREAD

**Issue by elmcrest** [vvidic/mjpeg-proxy#13]
hey everybody. first of all thx for this piece - really helps me with a rather annoying ip camera.

so, my setup is pretty normale I guess, I'm starting mjpeg-proxy like this:
```
./mjpeg-proxy --bind [::1]:5500 --rate 16.0 --source "http://mycam/control/faststream.jpg?stream=full&fps=16.0" > /dev/null 2>&1 &
```
I'm serving it with Nginx like this:
```
        location /stream {
                proxy_pass http://[::1]:5500;
        }
```
on my client (iPhone) I've added an `img` tag with the correct src.

problem ist now, after some timeout, the stream stops as expected and the imp tag's content is empty - so I don't see anything again.
As a solution I've added some eventListeners and I remove the src or add it back in on `visibilitychange` events.

now I can brute force mjpeg-proxy so to speak: when switching away from my client tab and switch back to it, I can see in the PubSub log, that each cycle adds a new Subscriber and doesn't close the not longer consumed one. I tried several things including remove the complete imp node from the DOM but I can't find a way to tell mjpeg-proxy that a particular consumer is gone.
"naturally" there is some kind of timeout happening if I stay away long enough from the tab/safari eventually all subscriber cancel the subscription - I can trigger the same with closing the tab or force-quitting Safari.

so, I'm not sure what else to do to further debug this so I thought you guys might be interested and might help me, please :)

let me know if I could provide additional information - disclaimer: I'm not a go developer.

If you have any other suggestions how to reliably (reconnecting) render a MJPEG stream please let me know.

**Comment by kescherCode** [comment]
This does not happen on my server at all (anymore), and the issue was previously thought to be fixed.

**Comment by elmcrest** [comment]
I'm on master and up-to-date.
Any Ideas how to debug this?

Edit: this seems to be an iOS only bug ... oh my!

**Comment by kescherCode** [comment]
Oof. You may want to check using debug methods I used in #8.

**Comment by elmcrest** [comment]
so, for now a kind of hard but working workaround is to listen on visibilitychange and if it's iOS and Safari ... `location.reload();` :D

**Comment by kescherCode** [comment]
Sure, but that's a client-side fix. For me, this indicates a bug in mjpeg-proxy itself... Hm.

**Comment by elmcrest** [comment]
well, if iOS is somehow too stupid and keeps the connection open you can't blame mjpeg-proxy then ... I'm currently installing bandwhich but it takes a moment on the raspi :P

**Comment by kescherCode** [comment]
Or is there perhaps an actual connection that stays open?

**Comment by elmcrest** [comment]
Ok complication failed, going to find another tool later... probably later today

and yes: can‘t rule this out right now.

**Comment by vvidic** [comment]
On the server side you can use `ss` or `lsof` to check if there is an open connection from client to nginx and another one from nginx to mjpeg-proxy. After that you can use `tcpdump` to record the request flow from the client when this happens.

I guess this might just be how the stream is handled in the browser. For example if I stop the stream (by pressing Esc) in Firefox it freezes the image, but leaves the connection open and receives data. Chrome on the other hand closes the connection and stops receiving.

You mention that "after some timeout, the stream stops as expected". I don't understand why the stream would stop after a timeout if the camera is still sending images?

**Comment by elmcrest** [comment]
ok, so I've figured that Safari isn't closing the connection - including on macOS.

```
:~$ sudo netstat -tupn | grep mjpeg-proxy
tcp        0      0 192.168.1.2:43672    192.168.1.3:80        ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55722               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55730               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55728               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55734               ESTABLISHED 2583/./mjpeg-proxy
:~$ sudo netstat -tupn | grep mjpeg-proxy
tcp        0      0 192.168.1.2:43672    192.168.1.3:80        ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55722               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55730               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55744               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55742               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55728               ESTABLISHED 2583/./mjpeg-proxy
tcp6       0      0 ::1:5500                ::1:55734               ESTABLISHED 2583/./mjpeg-proxy
:~$ sudo netstat -tupn | grep mjpeg-proxy
tcp        0      0 192.168.1.2:43672    192.168.1.3:80        ESTABLISHED 2583/./mjpeg-proxy
```

I've run the net stat command in between some "cycles of pushing my active safari tab in the background and foreground again". So it's pretty clear that Safari has a problem closing the connection once it's started and closes it only if:
1. you close the tab / window explicitely
2. you close Safari (with opened tab now in the background) and a timeout is reached -  only on iOS

so, I guess with mjpeg-proxy everything seems to be fine.

**Comment by kescherCode** [comment]
Alright. As such, this is NOT an issue with mjpeg-proxy? That's a relief to hear. Feel free to close this.

**Comment by elmcrest** [comment]
damn you Apple in case of Mjpeg
