### ISSUE TITLE
401 Unauthorized (digest?)

### ISSUE THREAD

**Issue by alpe12** [vvidic/mjpeg-proxy#14]
I can access my Dahua IPCam directly via _http://guest:guest@192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1_.
But `./mjpeg-proxy -source "http://192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1" -username guest -password guest` fails with:
```
chunker[/]: connecting to http://192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
pubsub[/]: failed to start chunker: request failed: 401 Unauthorized
```
`./mjpeg-proxy -source "http://guest:guest@192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1"` fails the same way.

PS: The autorization method of the camera is digest, not basic.

**Comment by vvidic** [comment]
Hi, thanks for the report. Digest auth is probably the problem here as the standard HTTP client in Go only supports Basic. I can try to add support for Digest if not too complicated.

**Comment by alpe12** [comment]
Thanks, @vvidic .
But sadly, didn't work.

This is a valid Authorization header for the camera:

`Digest username="guest", realm="Login to 5F081C5PAA97C82", nonce="1013271036", uri="/cgi-bin/mjpg/video.cgi?channel=1&subtype=1", response="6a24d3bbe8d2e3919b9d35738713cf4b", opaque="ca7ceff209adbf8604b72a8806f0bf9037fcfa5d", qop=auth, nc=00000001, cnonce="4e8b35306c153c8a"`

Apparently it needs more than this gives:

> return fmt.Sprintf(`username="%s", realm="%s", nonce="%s", response="%s", uri="%s"`,
> 		chunker.username, authMap["realm"], authMap["nonce"], response, uri)`

**Comment by vvidic** [comment]
Ok, I added support for more fields now, so you can try again.

**Comment by alpe12** [comment]
Same error. :/
I'm out of ideas now.

**Comment by alpe12** [comment]
It's working now. Thanks. <3

**Comment by alpe12** [comment]
Another issue now.
It prints a few frames, and then stop.

```
pubsub[/]: removed subscriber 192.168.1.60:58871 (total=0)
chunker[/]: failed: unexpected EOF
chunker[/]: stopping
pubsub[/]: added subscriber 192.168.1.60:59123 (total=1)
chunker[/]: connecting to http://192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
chunker[/]: started
chunker[/]: failed: unexpected EOF
chunker[/]: stopping
```

 I'll test it more tomorrow to see if I find something out.
