### ISSUE TITLE
Boundary changes with every request

### ISSUE THREAD

**Issue by alpe12** [vvidic/mjpeg-proxy#16]
Is this intended? If so, could you add a options to make it fixed?
The boundary of my camera is _--myboundary_. mjpeg-proxy uses a different boundary for every request.

eg:
> multipart/x-mixed-replace; boundary=97fe87f7600ea95da17778fce99c9d72218ff1513e778ee3892c60081cef
> multipart/x-mixed-replace; boundary=c690fd9c03c8d4cf408809d70a0ea8eec88b763f1f206fc173f132d9ff07

Also, I checked the response, and apparently the boundary used in the stream have "--" before, while the random boundary in the content-header does not. Maybe this is what causes https://github.com/vvidic/mjpeg-proxy/issues/14#issuecomment-794862708 .

eg:
The content-header is:
> multipart/x-mixed-replace; boundary=97fe87f7600ea95da17778fce99c9d72218ff1513e778ee3892c60081cef

but the stream actually uses:
> --97fe87f7600ea95da17778fce99c9d72218ff1513e778ee3892c60081cef

Connecting directly to my camera the boundary in the content-type is _--myboundary_ and _--myboundary_ is actually used in the stream.

**Comment by vvidic** [comment]
You can try to set a fixed boundary like this:

```
mw := multipart.NewWriter(w)
mw.SetBoundary("myboundary")
contentType := fmt.Sprintf("multipart/x-mixed-replace; boundary=%s", mw.Boundary())
```
but I don't think this will solve the problem.

It would be best to record the network traffic between mjpeg-proxy and camera, but also between client and mjpeg-proxy (using tcpdump, wireshark or something similar). That should show where the connection is breaking and why.

**Comment by vvidic** [comment]
Can you share what the initial response header from the camera looks like? It should be something like this:

```
   HTTP/1.1 200 OK
   Content-Type: multipart/x-mixed-replace;boundary=myboundary
   Cache-Control: no-cache
   Pragma: no-cache

   --myboundary
   Content-Type: image/jpeg
   Content-Length: 36291
```

**Comment by alpe12** [comment]
Making the boundary the same helped. Now it can go for a few minutes before breaking.
But once it breaks, only restarting it for it to work again.
Maybe it would start working again after -stopduration, but for that there should be a moment when 0 clients are conected.

>HTTP/1.1 200 OK
>Cache-Control: no-cache
>Pragma: no-cache
>Expires: Thu, 01 Dec 1994 16:00:00 GMT
>Connection: close
>Content-Type: multipart/x-mixed-replace; boundary=myboundary
>Transfer-Encoding: chunked

>--myboundary\r\nContent-Type: image/jpeg\r\nContent-Length: 33351\r\n\r\nÿØÿþ\u0000\u000f\n\u0001__________________\u001c{Ó¸ÿÙ\r\n--myboundary\r\nContent-Type: image/jpeg\r\nContent-Length: 33363\r\n\r\nÿØÿþ\u0000\u000f\n\u0001'sÊ«\"'sÊ«\"\u0001ÿþ\u0000\u000f\n\u0000_____________________\u0004RÄ\u001fÖª²85|JXÃzw\u0003ÿÙ\r\n--myboundary\r\nContent-Type: image/jpeg\r\nContent-Length: 34744\r\n\r\nÿØÿþ\u0000\u000f\n\u0001

**Comment by vvidic** [comment]
This output looks normal to me, so not sure what is going on. I assume some problem on the camera side that is breaking the stream of jpeg images. Perhaps you can try to verify that the camera stream works correctly with some other tool like curl.

**Comment by alpe12** [comment]
I tested with curl yesterday and it worked for about 10 minutes before I stopped the download.
Maybe the camera loses some frames and that causes mjpeg-proxy to disconnect? Curl wouldn't detect that.
Isn't it possible to add some code to mjpeg-proxy to detect that the stream isn't working anymore and to reconnect to it?
Having to manually restart is the main problem now.

I also noticed that when it stop working, sometimes the user count don't go down. Even after the client disconnected.

**Comment by BigNerd95** [comment]
I had problems with some camera not adding a "\n" after the preceding frame.
Eg:
Correct stream:
```
--boundary\n
headers\n
\n
frame\n    <-- new line!
--boundary
...
```

Incorrect stream:
```
--boundary\n
headers\n
\n
frame--boundary    <-- missing new line before boundary
...
```

If I open the camera stream in chrome it works, but whit this mjpeg proxy it freeze
I think the problem is here: https://github.com/golang/go/blob/master/src/mime/multipart/multipart.go#L369

Maybe this is the problem for you too?

**Comment by vvidic** [comment]
Currently `mjpeg-proxy` simply copies the camera stream and should continue working as long as the camera is sending something. We could add a retry but this will not help if the camera is still holding the connection open.

So it would be better if we could understand the problem first. For that we would need a `tcpdump` log of the connection to the camera, connection to the client and also the output of `mjpeg-proxy`.

**Comment by alpe12** [comment]
@BigNerd95 I noticed this too.

I'm testing with tcpdump and noticed that in addition to the error that make I have to restart it, sometimes the video freezes and never comes back. But looking at tcpdump it is still sending data to the client. So I think it's some problem with the boundary that keeps the browser waiting.



About the restart problem:

192.168.1.250 is the server.
192.168.1.108 is the camera.
https://pastebin.com/N4hh21xd

At 18:49:01 it stopped working. And tcpdump got stuck like this. Even after I closed mjpeg-proxy it remained this way.


https://pastebin.com/Jze7xwGB
The subscriber number going up is the client retrying.
Once mjpeg-proxy gets like this, only restarting it to fix it. Or waiting for the camera connection to close with -stopduration.

I'm still testing.

**Comment by alpe12** [comment]
It happened now.

My boundary is "--myboundary".
I was able to see what happened when one stream failed (without needing restart).

```
----myboundary
Content-Size: 34957
Content-Type: image/jpeg

ÿØÿþ
```

From this moment onwards it uses "----myboundary". Until I refresh the page.
This is why the browser freezes. It recognizes "--myboundary", but since there's an additional "--" it breaks the jpg.

**Comment by alpe12** [comment]
I replaced:
`contentType := fmt.Sprintf("multipart/x-mixed-replace; boundary=%s", mw.Boundary())`
with:
`contentType := fmt.Sprintf("multipart/x-mixed-replace; boundary=--%s", mw.Boundary())`
on pubsub.go.

And it's working for now. Way longer than before.
I will keep testing and update.


Edit: nevermind. stopped working.

Edit2:

To camera (192.168.1.108): https://pastebin.com/An4t3fm4
To client (192.168.1.60): https://pastebin.com/F9duSYjs

**Comment by vvidic** [comment]
I made some changes in the code. Not sure if it will help in your case, but you can give it a try.

**Comment by alpe12** [comment]
It streamed for almost 15m without breaking. And it restarted, as expected,  after that. I can live with that. Thanks.
> chunker[/]: failed: unexpected EOF

Is there anything I could try tweaking to try to keep the client connected, waiting, while it reconects to the camera?
Like when it gets unexpected EOF immediately opens a new stream without closing clients.
Maybe sending a blank frame, if it's needed to keep the client connected.

But like I said, I think I can live with the way it is now.

**Comment by alpe12** [comment]
```
chunker[/]: connecting to http://192.168.1.108/cgi-bin/mjpg/video.cgi?channel=1&subtype=1
chunker[/]: started
panic: send on closed channel

goroutine 35 [running]:
main.(*PubSub).doPublish(0x40001445c0, 0x40002f0000, 0x8859, 0xfe00)
        /media/alpe/42e85415-2b13-4e65-bff6-e01945d9ea67/temp/mjpeg-proxy/pubsub.go:111 +0xa0
main.(*PubSub).loop(0x40001445c0)
        /media/alpe/42e85415-2b13-4e65-bff6-e01945d9ea67/temp/mjpeg-proxy/pubsub.go:86 +0x210
created by main.(*PubSub).Start
        /media/alpe/42e85415-2b13-4e65-bff6-e01945d9ea67/temp/mjpeg-proxy/pubsub.go:70 +0x3c
```


If I kill php curl mid transfer, mjpeg-proxy keeps it as subscriber for several minutes. Maybe add a timeout? Or a check to confirm that the user is still connected.
This might be related to this panic error.

**Comment by alpe12** [comment]
Just noticed you are using "Content-Size". I think the correct (RFC 7233?) is to use "Content-Length".

**Comment by BigNerd95** [comment]
"Content-Length" or "Content-Size" are unnecessary in multipart stream.
In fact it is ignored and this is the reason why it is working with the wrong "Content-Size" header.
How you can see the RFC doesn't even talk about content length: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html
Each part is delimited by the boundary, so there is no need to communicate the size of the parts.
It is like SMTP, the body of the mail is delimited by the final dot, so there is no "mail length".
Even in other projects someone is talking about this: https://github.com/square/okhttp/issues/2138

**Comment by vvidic** [comment]
Updated the code to use the `Content-Length`.

Now about the panic, I can't see how that could happen with the current code. Is there some way to reproduce this?

**Comment by alpe12** [comment]
Serving something like this through php-fpm, acessing the page, and refreshing it before the timeout is reached.

```
<?php
$curl = curl_init();
curl_setopt_array($curl, [CURLOPT_URL => 'http://127.0.0.1:8050/', CURLOPT_VERBOSE => true, CURLOPT_TIMEOUT => 30, CURLOPT_HEADERFUNCTION => function ($curl, $header) use (&$headers)
{
    $len = strlen($header);
    $header = explode(':', $header, 2);
    if (count($header) < 2) return $len;
    if (strtolower(trim($header[0])) === 'content-type')
    {
        header("Content-type: " . trim($header[1]));
    }
    return $len;
}
]);
curl_exec($curl);
curl_close($curl); ?>
```

It's not always that it panics. Sometimes it takes a few refreshes.
But always the connection is kept as subscriber. This is another problem.

It probably happens because php-fpm with "pm = dynamic" keeps some processes running. But it (should) close the .php as soon as the client disconnect, so that shouldn't be a problem.

**Comment by alpe12** [comment]
Adding _pm.max_requests = 1_ to php-fpm works as a workaround. If you find a way to make mjpeg-proxy detect that the client disconnected, even if the php-fpm process is still running, it would be **way** better than using this option. But it's ok if not.

An option to set a timeout on subscribers would be good too. On my use case, I don't want clients to receive mjpeg for more than 30s straight. If it's easy to do, but you don't want to add it to the repository, can you tell me what to modify?

One (low priority) improvement that could be made:

> Is there anything I could try tweaking to try to keep the client connected, waiting, while mjpeg_proxy reconects to the camera?
> Like when it gets unexpected EOF immediately opens a new stream without closing clients.
> Maybe sending a blank frame, if it's needed to keep the client connected.
