### ISSUE TITLE
Is this append needed?

### ISSUE THREAD

**Issue by BigNerd95** [vvidic/mjpeg-proxy#5]
Here you are using append, but you are not providing other arguments to append.
I also compared the address returned and it is the same of the original data.
So why did you use it?

https://github.com/vvidic/mjpeg-proxy/blob/6920c7b6adb3a13f4b587f83ebcdc227e8b65021/mjpeg-proxy.go#L193

**Comment by kescherCode** [comment]
You could create a pull request to remove this append, if it is really unneeded.
